PruebaCirculAR/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('', include('Usuarios.urls',namespace='Usuarios')),
    path('', include('publicacion.urls',namespace='publicacion')),
    path('', include('compra.urls', namespace='compra')),
    path('',include('api.urls', namespace='api')),
    path('', include('inbox.urls',namespace='inbox')),
    path('', include('venta.urls',namespace='venta')),
    path('acerca/', views.acerca, name='acerca'),
    path('faq/', views.faq, name='faq'),
    path('terminos/', views.terminos, name='terminos'),
    path('privacidad/', views.privacidad, name='privacidad'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('procesar_pago/<int:publicacion_id>/', views.procesar_pago, name='procesar_pago'),
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('pago_fallido/', views.pago_fallido, name='pago_fallido'),
    path('pago_pendiente/', views.pago_pendiente, name='pago_pendiente'),
]

compra/urls.py
from django.urls import path
from . import views
from .views import trueque_realizado

app_name = 'compra'
urlpatterns = [
path('realizar_compra/<int:id>/', views.realizar_compra, name='realizar_compra'),
path('compra/compras_realizadas/', views.compras_realizadas, name='compras_realizadas'),
path('pago_efectivo/<int:publicacion_id>/', views.pago_efectivo, name='pago_efectivo'),
path('pago_transferencia/<int:publicacion_id>/', views.pago_transferencia, name='pago_transferencia'),
path('trueque/<int:publicacion_id>/', views.trueque_view, name='trueque'),
path('compra/trueque_realizado/', trueque_realizado, name='trueque_realizado'),
path('compra/publicado/<int:publicacion_id>/', views.publicado, name='publicado'),
path('compra/nuevoproducto/<int:publicacion_id>/', views.nuevo_producto, name='nuevo_producto'),
]

publicacion/urls.py
from django.urls import path
from . import views

app_name = 'publicacion'
urlpatterns = [
    path('publicaciones',views.publicaciones,name='publicaciones'),
    path('publicaciones_filtradas/<int:id>',views.publicaciones_filtradas,name='publicaciones_filtradas'),
    path('nueva_publicacion',views.nuevaPublicacion,name='nuevaPublicacion'),
    path('lista_publicaciones',views.lista_publicaciones,name='lista_publicaciones'),
    path('mostrar_publicacion/<int:id>',views.mostrar_publicacion,name='mostrar_publicacion'),
    path('modificar_publicacion/<int:id>',views.modificar_publicacion,name='modificar_publicacion'),
    path('eliminar_publicacion/<int:id>',views.eliminar_publicacion,name='eliminar_publicacion'),
    path ('buscar_publicacion', views.search, name='buscar_publicacion'),
]

venta/urls.py
from django.urls import path
from . import views

app_name = 'venta'
urlpatterns = [
    #path('venta/ventas_realizadas/', views.ventas_realizadas, name='ventas_realizadas'),
    path('ventas_realizadas/', views.ventas_realizadas, name='ventas_realizadas'),
    path('trueque/<int:trueque_id>/responder/<str:accion>/', views.responder_trueque, name='responder_trueque'),
    ]

venta/models.py
from django.conf import settings 
from django.db import models
#from django.contrib.auth.models import User
from Usuarios.models import CustomUser
from publicacion.models import Publicacion, Producto
from compra.models import Trueque

class Venta(models.Model):
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE,null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.publicacion.nombre} vendido por {self.usuario.username} el {self.fecha}"

venta/forms.py
from django import forms
from .models import Trueque

class RespuestaTruequeForm(forms.ModelForm):
    class Meta:
        model = Trueque
        fields = ['estado_trueque']
        widgets = {
            'estado_trueque': forms.Select(choices=[('aceptado', 'Aceptar'), ('rechazado', 'Rechazar')]),
        }

venta/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Venta, Publicacion,Trueque
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import RespuestaTruequeForm
from inbox.views import notificacion  


def lista_ventas(request):
    # Filtrar las ventas realizadas por el usuario actual
    ventas = Venta.objects.filter(usuario=request.user)
    return render(request, 'ventas_realizadas.html', {'ventas': ventas})

@login_required
def ventas_realizadas(request):

    ventas_realizadas = Publicacion.objects.filter(usuario=request.user, vigencia=3)
    
    context = {
        'ventas_realizadas': ventas_realizadas
    }
    return render(request, 'ventas_realizadas.html', context)


@login_required
def responder_trueque(request, trueque_id, accion,):
    trueque = get_object_or_404(Trueque, id=trueque_id, publicacion__usuario=request.user)


    if accion == 'aceptado':
        trueque.estado_trueque = 'aceptado'
        trueque.save()
        trueque.respuesta_vendedor = 'Tu oferta ha sido aceptada.'
        messages.success(request, 'Has aceptado el trueque.')
        notificacion(request, trueque, 4)

    elif accion == 'rechazado':
        trueque.estado_trueque = 'rechazado'
        trueque.save()
        publicacion = trueque.publicacion
        publicacion.vigencia = 1
        publicacion.save()
        trueque.respuesta_vendedor = 'Tu oferta ha sido rechazada.'
        messages.success(request, 'Has rechazado el trueque.')
        notificacion(request, trueque, 5)

 
    trueque.save()

    return redirect('compra:trueque_realizado')

venta/templates/responder_trueque.html
{% extends "base.html" %}

{% block content %}
<h2>Responder al Trueque</h2>

<p><strong>Producto Ofrecido:</strong> {{ trueque.producto_ofrecido }}</p>
<p><strong>Mensaje del Usuario:</strong> {{ trueque.usuario.get_username }}</p>

<a href="{% url 'compra:responder_trueque' trueque.id 'aceptar' %}" class="btn btn-success">Aceptar Trueque</a>
<a href="{% url 'compra:responder_trueque' trueque.id 'rechazar' %}" class="btn btn-danger">Rechazar Trueque</a>
{% endblock %}

venta/templates/ventas_realizadas.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <br>
    <br>
    <ul class="nav nav-tabs">
       
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'publicacion:lista_publicaciones' %}">Mis Publicaciones</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'compra:compras_realizadas' %}">Mis Compras</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'compra:trueque_realizado' %}">Mis Trueques</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark active" aria-current="page" href="{% url 'venta:ventas_realizadas' %}">Mis Ventas</a>
        </li>
    </ul>
    <br>
    <h1>Lista de ventas:</h1>
    <br>
    <br>
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 22%;">NOMBRE DE LA PUBLICACIÓN</th>
                    <th style="width: 22%;">FECHA</th>
                    <th style="width: 22%;">PRECIO</th>
                    <th style="width: 22%;">IMAGEN</th>
                </tr>
            </thead>
            <tbody>
                {% for venta in ventas_realizadas %}
                <tr>   
                    <td>{{ venta.nombre }}</td>
                    <td>{{ venta.fecha }}</td>
                    <td>{{ venta.valor }}</td>
                    <td><svg class="bi" width="24" height="24"></svg>
                        <img src="{{ venta.producto.imagen_1.url }}" class="img-fluid" width="100" height="100" />
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">No tienes ventas realizadas.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}