PruebaCirculAR/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('', include('Usuarios.urls',namespace='Usuarios')),
    path('', include('publicacion.urls',namespace='publicacion')),
    path('', include('compra.urls', namespace='compra')),
    path('',include('api.urls', namespace='api')),
    path('', include('inbox.urls',namespace='inbox')),
    path('', include('venta.urls',namespace='venta')),
    path('acerca/', views.acerca, name='acerca'),
    path('faq/', views.faq, name='faq'),
    path('terminos/', views.terminos, name='terminos'),
    path('privacidad/', views.privacidad, name='privacidad'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('procesar_pago/<int:publicacion_id>/', views.procesar_pago, name='procesar_pago'),
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('pago_fallido/', views.pago_fallido, name='pago_fallido'),
    path('pago_pendiente/', views.pago_pendiente, name='pago_pendiente'),
]

compra/urls.py
from django.urls import path
from . import views
from .views import trueque_realizado

app_name = 'compra'
urlpatterns = [
path('realizar_compra/<int:id>/', views.realizar_compra, name='realizar_compra'),
path('compra/compras_realizadas/', views.compras_realizadas, name='compras_realizadas'),
path('pago_efectivo/<int:publicacion_id>/', views.pago_efectivo, name='pago_efectivo'),
path('pago_transferencia/<int:publicacion_id>/', views.pago_transferencia, name='pago_transferencia'),
path('trueque/<int:publicacion_id>/', views.trueque_view, name='trueque'),
path('compra/trueque_realizado/', trueque_realizado, name='trueque_realizado'),
path('compra/publicado/<int:publicacion_id>/', views.publicado, name='publicado'),
path('compra/nuevoproducto/<int:publicacion_id>/', views.nuevo_producto, name='nuevo_producto'),
]

publicacion/urls.py
from django.urls import path
from . import views

app_name = 'publicacion'
urlpatterns = [
    path('publicaciones',views.publicaciones,name='publicaciones'),
    path('publicaciones_filtradas/<int:id>',views.publicaciones_filtradas,name='publicaciones_filtradas'),
    path('nueva_publicacion',views.nuevaPublicacion,name='nuevaPublicacion'),
    path('lista_publicaciones',views.lista_publicaciones,name='lista_publicaciones'),
    path('mostrar_publicacion/<int:id>',views.mostrar_publicacion,name='mostrar_publicacion'),
    path('modificar_publicacion/<int:id>',views.modificar_publicacion,name='modificar_publicacion'),
    path('eliminar_publicacion/<int:id>',views.eliminar_publicacion,name='eliminar_publicacion'),
    path ('buscar_publicacion', views.search, name='buscar_publicacion'),
]

venta/urls.py
from django.urls import path
from . import views

app_name = 'venta'
urlpatterns = [
    #path('venta/ventas_realizadas/', views.ventas_realizadas, name='ventas_realizadas'),
    path('ventas_realizadas/', views.ventas_realizadas, name='ventas_realizadas'),
    path('trueque/<int:trueque_id>/responder/<str:accion>/', views.responder_trueque, name='responder_trueque'),
    ]

publicacion/models.py
from django.db import models
from Usuarios.models import CustomUser

# Create your models here.
class Rubro(models.Model):
    nombre = models.CharField(max_length=50)
    imagen = models.ImageField(null=True, blank=True, upload_to='images/', default='images/sin_Imagen.png')

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    imagen_1 = models.ImageField(null=True, blank=True, upload_to='images/', default='images/sin_Imagen.png')
    imagen_2 = models.ImageField(null=True, blank=True, upload_to='images/', default='images/sin_Imagen.png')
    imagen_3 = models.ImageField(null=True, blank=True, upload_to='images/', default='images/sin_Imagen.png')
    
    
    def __str__(self):
        return self.nombre

ELECCION_ESTADO=[
    (1,'Muy bueno'),
    (2,'Bueno'),
    (3,'Regular'),
    (4,'Reparar')
]

ELECCION_VIGENCIA=[
    (1,'VIGENTE'),
    (2,'ELIMINADO'),
    (3,'SUSPENDIDO')
]

class Publicacion(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(max_length=200)
    valor = models.DecimalField(decimal_places=2,max_digits=9)
    estado=models.IntegerField(choices=ELECCION_ESTADO,default=1,null=False,blank=False)
    descuento = models.IntegerField(null=True,blank=True)
    vigencia = models.IntegerField(choices=ELECCION_VIGENCIA,default=1,null=False,blank=False)
    rubro = models.ForeignKey(Rubro, on_delete=models.CASCADE,null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    comentarios = models.IntegerField(default=0, null=False,blank=False)

    def __str__(self):
        return self.nombre

publicacion/views.py
from django.shortcuts import get_object_or_404,render,redirect
from django.contrib.auth.decorators import login_required
from .forms import PublicacionForm,ProductoForm,ModificarProductoForm,ModificarPublicacionForm,EliminarPublicacionForm
from .models import Publicacion,Producto,CustomUser, Rubro
from django.forms.models import inlineformset_factory
from chat.models import Meep
from chat.forms import MeepForm
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator
from inbox.views import notificacion

# Create your views here.
@login_required
def nuevaPublicacion(request):

    lista_publicaciones = Publicacion.objects.all().order_by('-id').filter(usuario=request.user.id, vigencia=1)

    submitted = False

    # Definición del FormSet
    PublicacionFormSet = inlineformset_factory(
        Producto, 
        Publicacion, 
        form=PublicacionForm, 
        fields=['nombre', 'descripcion', 'rubro', 'estado', 'valor', 'descuento'],
        can_delete=False, 
        extra=1
    )

    # Inicializa el formulario y el FormSet
    form = ProductoForm()
    publicacionFormSet = PublicacionFormSet()

    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            producto = form.save()
            publicacionFormSet = PublicacionFormSet(request.POST, instance=producto)
            if publicacionFormSet.is_valid():
                publicaciones = publicacionFormSet.save(commit=False)
                for publicacion in publicaciones:
                    publicacion.usuario = request.user
                    publicacion.save()
                submitted = True
            else:
                # Eliminar el producto si hubo un error con el FormSet
                producto.delete()
                messages.error(request, "Ha ocurrido un error al cargar la publicación...")
        else:
            # Inicializar FormSet vacío en caso de que el formulario `ProductoForm` no sea válido
            publicacionFormSet = PublicacionFormSet()

    context = {
        'form': form,
        'publicacionFormSet': publicacionFormSet,
        'submitted': submitted,
        'lista_publicaciones': lista_publicaciones
    }

    return render(request, 'nueva_publicacion.html', context)

#@login_required
#def lista_publicaciones(request):
 #   lista_publicaciones = Publicacion.objects.all().order_by('-id').filter(usuario=request.user.id).exclude(vigencia=2)
  #  context={
   #     'lista_publicaciones': lista_publicaciones
    #}
    #return render(request,'lista_publicaciones.html',context)

@login_required
def lista_publicaciones(request):

    lista_publicaciones = Publicacion.objects.all().order_by('-id').filter(usuario=request.user.id, vigencia=1).exclude(vigencia=2)
    context={
    # Filtrar publicaciones del usuario actual que estén en estado "VIGENTE" (excluir ELIMINADO y SUSPENDIDO)
        'lista_publicaciones': lista_publicaciones
    }
    return render(request, 'lista_publicaciones.html', context)

   
def publicaciones(request):
    rubros=Rubro.objects.all()
    publicacion = Publicacion.objects.all().filter(vigencia=1).order_by('-id')
    p = Paginator(Publicacion.objects.all().filter(vigencia=1).order_by('-id'), 6)
    page= request.GET.get('page' )
    pub=p.get_page(page)
    nums = "a" * pub.paginator.num_pages

    context={
        'rubros': rubros,
        'publicacion': publicacion,
        'pub': pub,
        'nums': nums
    }
    return render(request,'publicaciones.html',context)

    
def publicaciones_filtradas(request, id):
    rubros=Rubro.objects.all()
    if id < 5:
       publicacion = Publicacion.objects.all().filter(rubro=id, vigencia=1).order_by('-id')
       p = Paginator(Publicacion.objects.all().filter(rubro=id, vigencia=1).order_by('-id'),6)
       page= request.GET.get('page' )
       pub=p.get_page(page)
       nums = "a" * pub.paginator.num_pages

    elif id == 5:
        publicacion = Publicacion.objects.all().filter(vigencia=1).order_by('id')
        p = Paginator(Publicacion.objects.all().filter(vigencia=1).order_by('id'),6)
        page= request.GET.get('page' )
        pub=p.get_page(page)
        nums = "a" * pub.paginator.num_pages

    elif id == 6:
        publicacion = Publicacion.objects.all().filter(vigencia=1).order_by('-id')
        p = Paginator(Publicacion.objects.all().filter(vigencia=1).order_by('-id'),6)
        page= request.GET.get('page' )
        pub=p.get_page(page)
        nums = "a" * pub.paginator.num_pages

    elif id == 7:
        publicacion = Publicacion.objects.all().filter(vigencia=1).order_by('-valor')
        p = Paginator(Publicacion.objects.all().filter(vigencia=1).order_by('-valor'),6)
        page= request.GET.get('page' )
        pub=p.get_page(page)
        nums = "a" * pub.paginator.num_pages

    elif id == 8:
        publicacion = Publicacion.objects.all().filter(vigencia=1).order_by('valor')
        p = Paginator(Publicacion.objects.all().filter(vigencia=1).order_by('valor'),6)
        page= request.GET.get('page' )
        pub=p.get_page(page)
        nums = "a" * pub.paginator.num_pages      

    context={
        'publicacion': publicacion,
        'id': id,
        'pub': pub,
        'nums': nums,
        'rubros': rubros
    }
    return render(request,'publicaciones_filtradas.html',context)


@login_required
def mostrar_publicacion(request, id):
    publicacion = get_object_or_404(Publicacion, pk=id)
    
    # Obtener el nombre del estado
    estado_nombre = publicacion.get_estado_display()

    if request.method == "POST":
        form = MeepForm(request.POST or None)

        publica=get_object_or_404(Publicacion,pk=id)
        if request.method == "POST":
            if form.is_valid():
                meep = form.save(commit=False)
                meep.user = request.user
                meep.publicacion=publica.id
                meep.save()
                notificacion(request,publica,1)
                messages.success(request, ('Tu consulta ha sido publicada'))
                return redirect('publicacion:mostrar_publicacion', publica.id)
        publicacion=get_object_or_404(Publicacion,pk=id)
        publicados=Publicacion.objects.all().filter(usuario=publicacion.usuario,vigencia=1).exclude(pk=id)[:4]
        vendedor=CustomUser.objects.all().filter(username=publicacion.usuario)
        meeps=Meep.objects.all().filter(publicacion=id).order_by("-created_at")
        meeps_cantidad=Meep.objects.filter(publicacion=id).count()
        Publicacion.objects.filter(pk=id).update(comentarios=meeps_cantidad)
        context={
            'publicacion':publicacion,
            'publicados':publicados,
            'vendedor' :vendedor,
            'meeps':meeps,
            'meeps_cantidad': meeps_cantidad, 
            'form':form
        }
        return render(request,'mostrar_publicacion.html',context)
    
    else:
        publicacion=get_object_or_404(Publicacion,pk=id)
        publicados=Publicacion.objects.all().filter(usuario=publicacion.usuario,vigencia=1).exclude(pk=id)[:4]
        vendedor=CustomUser.objects.all().filter(username=publicacion.usuario)
        meeps=Meep.objects.all().filter(publicacion=id).order_by("-created_at")
        form = MeepForm(request.POST or None) if request.user.is_authenticated else None
        context={
            'publicacion':publicacion,
            'publicados':publicados,
            'vendedor' :vendedor,
            'form': form,
            'meeps':meeps
        }
        return render(request,'mostrar_publicacion.html',context)
    
   
@login_required
def modificar_publicacion(request,id):
    publicacion=get_object_or_404(Publicacion,pk=id)
    producto=get_object_or_404(Producto,pk=publicacion.producto.pk)
    PublicacionFormSet = inlineformset_factory(Producto,Publicacion,form=ModificarPublicacionForm,fields=['nombre','descripcion','rubro','estado','valor','descuento'],can_delete=False,max_num=1)
    if request.method == 'POST':
        form=ModificarProductoForm(request.POST, request.FILES, instance=producto)
        publicacionFormSet = PublicacionFormSet(request.POST,instance=producto)
        if form.is_valid() and publicacionFormSet.is_valid():
            form.save()
            publicacionFormSet.save()
            context={
                'publicacion':get_object_or_404(Publicacion,pk=id)
            }
            messages.success(request,"La publicación ha sido actualizada")
            return render(request,'mostrar_publicacion.html',context)
    else:
        form = ModificarProductoForm(instance=producto)
        publicacionFormSet=PublicacionFormSet(instance=producto)
    context={
        'form':form,
        'publicacionFormSet':publicacionFormSet,
        'publicacion':publicacion
    }
    return render(request,'modificar_publicacion.html',context)

@login_required
def eliminar_publicacion(request,id):
    publicacion=get_object_or_404(Publicacion,pk=id)
    if request.method == 'POST':
        publicacion.vigencia=2
        publicacion.save()
        messages.success(request,"La publicación se ha eliminado")
        return redirect('publicacion:lista_publicaciones')
    else:
        form=EliminarPublicacionForm(instance=publicacion)
    context={
            'form':form
            }
    return render(request, 'eliminar_publicacion.html', context)

def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        if searched != '':
            #busco los productos
            searched = Publicacion.objects.filter(Q(nombre__icontains=searched) | Q(descripcion__icontains=searched)).filter(vigencia=1)
            total_search = searched.count()
            rubros=Rubro.objects.all()

            searched_1 = searched.filter(rubro=1)
            total_search_1 = searched_1.count()
            rubros_1 = rubros.filter(id=1)

            searched_2 = searched.filter(rubro=2)

publicacion/templates/lista_publicaciones.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <br>
    <br>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link text-dark active" aria-current="page" href="{% url 'publicacion:lista_publicaciones' %}">Mis Publicaciones</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'compra:compras_realizadas' %}">Mis Compras</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'compra:trueque_realizado' %}">Mis Trueques</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'venta:ventas_realizadas' %}">Mis Ventas</a>
        </li>
    </ul>
    <br>
    <h1>Lista de Publicaciones de: {{ user.username }}</h1>
    <br>
    <div class="d-grid gap-3 d-md-block">
        <a class="btn btn-info" role="button" href="{% url 'publicacion:nuevaPublicacion' %}">Ingresar producto</a>
    </div>
    <br>
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    
                    <th style="width: 22%;">PUBLICACIÓN</th>
                    <th style="width: 22%;">DESCRIPCIÓN</th>
                    <th style="width: 22%;">RUBRO</th>
                    <th style="width: 22%;">PRECIO</th>
                    <th style="width: 22%;">IMAGEN1</th>
                    <th style="width: 22%;">Consultas</th>
                </tr>
            </thead>
            <tbody>
                {% for publicacion in lista_publicaciones %}
                <tr>
                    <td><svg class="bi" width="24" height="24"></svg>
                        {{ publicacion.nombre }}
                    </td>
                    <td><svg class="bi" width="24" height="24"></svg>
                        {{ publicacion.descripcion }}
                    </td>
                    <td><svg class="bi" width="24" height="24"></svg>
                        {{ publicacion.rubro }}
                    </td>
                    <td><svg class="bi" width="24" height="24"></svg>
                        {{ publicacion.valor }}
                    </td>
                    <td><svg class="bi" width="24" height="24"></svg>
                        <img src="{{ publicacion.producto.imagen_1.url }}" class="img-fluid" width="300" height="300" />
                    </td>
                    <td><svg class="bi" width="24" height="24"></svg>
                        {{ publicacion.comentarios }}
                    </td>
                    <td>
                        <a href="{% url 'publicacion:mostrar_publicacion' id=publicacion.id %}"><span class="btn  btn-success btn-sm fw-light">Ver</span></a>
                    </td>
                    <td>
                        <a href="{% url 'publicacion:modificar_publicacion' id=publicacion.id %}"><span class="btn btn-primary btn-sm fw-light" >Modificar</span></a>                    </td>
                    <td>
                        <a href="{% url 'publicacion:eliminar_publicacion' id=publicacion.id %}"><span class="btn btn-danger btn-sm fw-light">Borrar</span></a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                  <td></td>
                  <td></td>
                  <td></td> 
                  <td colspan="6">Todavia no tienes productos publicados.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <br>
    <br>
    <br>
</div>
{% endblock %}

publicacion/templates/mostrar_publicacion.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'static/Style.css' %}">
<div class="container">

    <br>
    <br>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'publicacion:publicaciones' %}" class="text-dark fw-bold text-decoration-none">Publicaciones</a>
            </li>
            <li class="breadcrumb-item active text-dark fw-bold" aria-current="page">{{ publicacion.rubro }}</li>
        </ol>
    </nav>
    <hr class="my-4">
    <div class="row">
        <div class="col-sm-2">
            <div class="card mb-4">
                <div class="card-body center">

                    <div id="thumbs">
                        <img data-year="1" src="{{ publicacion.producto.imagen_1.url }}" class="img-thumbnail"
                            width="100" height="70" />
                        <img data-year="2" src="{{ publicacion.producto.imagen_2.url }}" class="img-thumbnail"
                            width="100" height="70" />
                        <img data-year="3" src="{{ publicacion.producto.imagen_3.url }}" class="img-thumbnail"
                            width="100" height="70" />
                    </div>
                    <br>
                    <br>
                </div>
            </div>
            <img src="{% static 'quality-control_12340770.gif' %}" alt="Descripción de la imagen" class="img-fluid" style="max-width: 70%; height: auto;">
        </div>
        <br>
        <br>
        <div class="col-sm-5">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="image-container">
                        <!-- Imagen principal con el efecto de zoom -->
                        <img id="imagenGrande" class="img-fluid" src="{{ publicacion.producto.imagen_1.url }}" />
                    </div>
                </div>
            </div>
        </div>
        
        <br>
        <br>
        <div class="col-sm-5">
            <div class="card mb-4 texto">
                <div class="card-body">
                    <h5 class="card-title">{{ publicacion.nombre}}</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">NOMBRE DE LA PUBLICACIÓN: {{ publicacion.nombre}}</li>
                        <li class="list-group-item">DESCRIPCIÓN: {{ publicacion.descripcion }}</li>
                        <li class="list-group-item">RUBRO: {{ publicacion.rubro }}</li>

                        <li class="list-group-item">VENDEDOR: {{ publicacion.usuario }}</li>
                        {% if vendedor %}
                        {% for vendedor in vendedor %}
                                                
                        <li class="list-group-item"> 
                           <img src="{{ vendedor.avatar.url }}" class="img-thumbnail" width="100" height="70" />
                        </li>

                        {% endfor %}
                        {% endif %}

                        <li class="list-group-item"></li>
                    </ul>
                    <h6 class="card-title">PRECIO $: {{ publicacion.valor }}</h6>
                    <h6 class="card-title success">DESCUENTO $: {{ publicacion.descuento }}</h6>
                </div>
                <div class="card-footer bg-transparent">
                    <div class="d-grid gap-2 col-6 mx-auto">
                        <a href="{% url 'compra:realizar_compra' publicacion.id %}"><span class="btn btn-success" type="button" >Realizar compra</span></a>
                        <a href="{% url 'publicacion:lista_publicaciones' %}"><span class="btn btn-warning form-control"  >Volver</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
            <div class="container text-center">
                <div class="row">
                    <div class="col-8" style="overflow-y: scroll; height: 600px;">
                        {% if meeps %}
                        {% for meep in meeps %}
                            {% if publicacion.usuario == meep.user %}
                            <div class="alert alert-warning" role="alert">
                                <div class="container">
                                    <div class="row">
                                            <div class="col-sm-1">
    
                                            <img src="../{{ meep.user.avatar }}" alt="usuario" width="50" class="rounded-circle me-2">
    
                                        </div> 
                                        <div class="col-sm-11">
    
                                            {{ meep.body }}
                                            <small class="text-muted"><br />
                                                {{ meep.created_at}} By
                                                {{ meep.user.username }}
                                            </small>
    
                                        </div>
                                    
                                    </div>    
    
                                </div>        
                                </div>
                                <br>
                                <br>
                                {% else %}
                                <div class="alert alert-dark" role="alert">
                                    <div class="container">
                                        <div class="row">
                                                <div class="col-sm-1">
        
                                                <img src="../{{ meep.user.avatar }}" alt="usuario" width="50" class="rounded-circle me-2">
        
                                            </div> 
                                            <div class="col-sm-11">
        
                                                {{ meep.body }}
                                                <small class="text-muted"><br />
                                                    {{ meep.created_at}} By
                                                    {{ meep.user.username }}
                                                </small>
        
                                            </div>
                                        
                                        </div>    
        
                                    </div>        
                                    </div>
                                <br>
                                <br>
                            {% endif %}
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-4">
                        {% if form %}
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-secondary">Pregunta!!</button>
                        </form>
                        
                        {% endif %}
                    </div>
                </div>
            </div>
            <br>
            <br>
        </div>
       
    </div>
</div>
<div class="container col-xxl-8 px-2 py-3"></div>
    <h3>Mas publicaciones del mismo Vendedor</h3>
    <hr class="my-4">
    
    <div class="card border-light">
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for publicacion in publicados %}
    
    <div class="col">
        <a href="{% url 'publicacion:mostrar_publicacion' id=publicacion.id %}" class="text-decoration-none text-dark card-link">
            <div class="card h-100 card-hover">
                <div class="image-container">
                    <img src="{{ publicacion.producto.imagen_1.url }}" class="card-img-top card-img-hover" alt="Imagen del producto">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ publicacion.nombre }}</h5>
                    <p class="card-text">{{ publicacion.descripcion}}</p>
                    <p class="card-text"><small class="text-body-secondary">${{ publicacion.valor }}</small></p>
                </div>
            </div>
        </a>
    </div>
    
    {% endfor %}
</div>
</div>
</div>
</div>

    {% endblock %}

publicacion/templates/nueva_publicacion.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="container">
    <br>
    <br>
    <h1>Ingresar nueva publicación</h1>
    <br>
    <br>
    {% if submitted %}
    <div class="container">
        <br>
        <br>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col">
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3 texto">
                        <h4 class="my-0 fw-normal">Publicación</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">Felicitaciones!!</h1>
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Su Publicación</li>
                            <li>ha sido</li>
                            <li>Ingresada</li>
                        </ul>
                        <a href="{% url 'publicacion:nuevaPublicacion' %}"><span class="btn btn-success">OK</span></a>
                    </div>
                </div>
            </div>
            <div class="col">
            </div>
        </div>
        <br>
        <br>
    </div>
    {% else %}
    <div class="row">
        <div class="col-sm-7">
            <div class="card mb-4 texto">
                <div class="card-body">
                    <form class="row g-3" action="" method=POST enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ publicacionFormSet.as_p }}
                        {{ form.as_p }}
                        <input type="submit" value="Publicar" class="btn btn-success">
                        <a href="{% url 'publicacion:lista_publicaciones' %}"><span class="btn btn-warning form-control" >Volver</span></a>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card mb-12" style="overflow-y: scroll; height: 600px;">
                <div class="card-header">Lista de Publicaciones Ingresadas</div>
                <div class="card-body text-primary">
                    <div class="tab-content" id="nav-tabContent">
                        <div class="tab-pane fade show active" role="tabpanel" aria-labelledby="nav-home-tab">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col"></th>
                                        <th scope="col">Nombre</th>
                                        <th scope="col">Descripcion</th>
                                        <th scope="col">Valor</th>
                                        <th scope="col">Rubro</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for publicacion in lista_publicaciones %}
                                    <tr>
                                        <td><a href="{% url 'publicacion:mostrar_publicacion' id=publicacion.id %}"><span class="btn btn-success">Mostrar</span></a></td>
                                        <td>{{ publicacion.nombre }}</td>
                                        <td>{{ publicacion.descripcion }}</td>
                                        <td>{{ publicacion.valor }}</td>
                                        <td>{{ publicacion.rubro }}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6 d-flex justify-content-center">
            <img src="{% static 'press-day_15747304 (1).gif' %}" alt="Descripción de la imagen" class="img-fluid" style="max-width: 30%; height: auto;">
        </div>
    </div>
    <br>
    <br>
    {% endif %}
</div>
{% endblock %}