PruebaCirculAR/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('', include('Usuarios.urls',namespace='Usuarios')),
    path('', include('publicacion.urls',namespace='publicacion')),
    path('', include('compra.urls', namespace='compra')),
    path('',include('api.urls', namespace='api')),
    path('', include('inbox.urls',namespace='inbox')),
    path('', include('venta.urls',namespace='venta')),
    path('acerca/', views.acerca, name='acerca'),
    path('faq/', views.faq, name='faq'),
    path('terminos/', views.terminos, name='terminos'),
    path('privacidad/', views.privacidad, name='privacidad'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Usuarios/urls.py
from django.urls import path
from . import views

app_name='Usuarios'
urlpatterns = [
    path('registrar',views.registrar,name='registrar'),
    path('salir',views.salir,name='salir'),
    path('ingresar',views.ingresar,name='ingresar'),
    path('modificar',views.modificar,name='modificar'),
    path('eliminar',views.eliminar,name='eliminar'),
    path('misDatos',views.misDatos,name='misDatos'),
]

api/urls.py
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('procesar_pago/<int:publicacion_id>/', views.procesar_pago, name='procesar_pago'),
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('pago_fallido/', views.pago_fallido, name='pago_fallido'),
    path('pago_pendiente/', views.pago_pendiente, name='pago_pendiente'),
]

compra/urls.py
from django.urls import path
from . import views
from .views import trueque_realizado

app_name = 'compra'
urlpatterns = [
path('realizar_compra/<int:id>/', views.realizar_compra, name='realizar_compra'),
path('compra/compras_realizadas/', views.compras_realizadas, name='compras_realizadas'),
path('pago_efectivo/<int:publicacion_id>/', views.pago_efectivo, name='pago_efectivo'),
path('pago_transferencia/<int:publicacion_id>/', views.pago_transferencia, name='pago_transferencia'),
path('trueque/<int:publicacion_id>/', views.trueque_view, name='trueque'),
path('compra/trueque_realizado/', trueque_realizado, name='trueque_realizado'),
path('compra/publicado/<int:publicacion_id>/', views.publicado, name='publicado'),
path('compra/nuevoproducto/<int:publicacion_id>/', views.nuevo_producto, name='nuevo_producto'),
]

inbox/urls.py
from django.urls import path
from . import views

app_name='inbox'
urlpatterns = [
    path('inbox',views.inbox,name='inbox'),
    path('conversacion/<conversacion_id>',views.inbox,name='inbox'),
]

publicacion/urls.py
from django.urls import path
from . import views

app_name = 'publicacion'
urlpatterns = [
    path('publicaciones',views.publicaciones,name='publicaciones'),
    path('publicaciones_filtradas/<int:id>',views.publicaciones_filtradas,name='publicaciones_filtradas'),
    path('nueva_publicacion',views.nuevaPublicacion,name='nuevaPublicacion'),
    path('lista_publicaciones',views.lista_publicaciones,name='lista_publicaciones'),
    path('mostrar_publicacion/<int:id>',views.mostrar_publicacion,name='mostrar_publicacion'),
    path('modificar_publicacion/<int:id>',views.modificar_publicacion,name='modificar_publicacion'),
    path('eliminar_publicacion/<int:id>',views.eliminar_publicacion,name='eliminar_publicacion'),
    path ('buscar_publicacion', views.search, name='buscar_publicacion'),
]

PruebaCirculAR/views.py
from django.shortcuts import render
from publicacion.models import Publicacion, Rubro 
from inbox.models import Conversacion

def home(request):
    rubro = Rubro.objects.all()[:4]
    lista_prod_rand = Publicacion.objects.all().filter(vigencia=1).order_by('?')[:4]
    lista_prod_last = Publicacion.objects.all().filter(vigencia=1).order_by('-id')[:4]
    if request.method=='GET':
        usuario=request.user
        notificacion=False
        if usuario.is_authenticated:
            for conversacion in Conversacion.objects.filter(participantes=request.user):
                ultimo_mensaje=conversacion.mensajes.last()
                if (conversacion.fue_visto == False) and (ultimo_mensaje.remitente != request.user):
                    notificacion=True
    context={
            'usuario':usuario,
            'lista_prod_rand': lista_prod_rand, 
            'lista_prod_last':lista_prod_last,
            'notificacion':notificacion,
            'rubro': rubro
            }
    return render(request,'home.html',context)
##aversers


def acerca(request):
    return render(request, 'footer_info.html')

def faq(request):
    return render(request, 'footer_info.html')

def terminos(request):
    return render(request, 'footer_info.html')

def privacidad(request):
    return render(request, 'footer_info.html')

PruebaCirculAR/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="icon" href="{% static 'Logo.ico' %}" type="image/x-icon"> 
    <title>CirculAr</title>
    <!-- CSS files -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Bootstrap Iconos -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <!-- <link rel="stylesheet" href="styles.css"> -->
    <style>
        .card-img-top {
            width: 100%;
            height: 20vw;
            object-fit: cover;
        }
    </style>
</head>

<body class="fade-in">
	{% load static %}
    {% include "file_header.html" %}
    <div class="container">
        {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
         {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
    {% include "file_footer.html" %}
    
    <!-- JS files -->
    <!-- jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
	<script src="{% static 'inbox.js' %}"></script>

    <!-- Script for image selection (already in your code) -->
    <script>
        $(document).ready(function () {
            //selector de imagenes a aplicar la funcionalidad de click
            $("#thumbs img").click(function () {
                //obtenemos la imagen a mostrar
                urlImagenGrande = $(this).data("year");
                if (urlImagenGrande == 1) {
                    //asignamos la imagen por medio de prop
                    $("#imagenGrande").prop("src", "{{ publicacion.producto.imagen_1.url }}");
                } else if (urlImagenGrande == 2) {
                    //asignamos la imagen por medio de prop
                    $("#imagenGrande").prop("src", "{{ publicacion.producto.imagen_2.url }}");
                } else {
                    //asignamos la imagen por medio de prop
                    $("#imagenGrande").prop("src", "{{ publicacion.producto.imagen_3.url }}");
                }
            });
        });
    </script>

    <!-- Fade-in and fade-out transition script -->
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const body = document.querySelector('body');
            
            // Aplica fade-in cuando la página carga
            body.classList.add('fade-in');
        
            // Escucha clics en todos los enlaces
            document.querySelectorAll('a').forEach(function (link) {
                link.addEventListener('click', function (event) {
                    event.preventDefault();
                    body.classList.add('fade-out');
                    
                    // Espera el tiempo de la transición antes de cambiar de página
                    setTimeout(function () {
                        window.location.href = link.href;
                    }, 800); // Tiempo igual a la duración del fade-out en CSS (0.8s)
                });
            });
        });
    </script>
</body>

</html>

PruebaCirculAR/templates/file_footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'Style.css' %}">
<!-- Footer -->
<footer class="text-center text-lg-start bg-body-tertiary text-muted">
    <!-- Section: Social media -->
    
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="box">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>CIRCULAR
            </h6>
            <H6>
              Somos la primer pagina de venta de Usados de 
              TODA la Argentina..
            </H6>
          </div>
          <!-- Grid column -->
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Productos
            </h6>
            <h6>
              <a href="https://circular.pythonanywhere.com/publicaciones" class="text-reset">Indumentaria</a>
            </h6>
            <h6>
              <a href="https://circular.pythonanywhere.com/publicaciones" class="text-reset">Rodados</a>
            </h6>
            <h6>
              <a href="https://circular.pythonanywhere.com/publicaciones" class="text-reset">Electrodomesticos</a>
            </h6>
            <h6>
              <a href="https://circular.pythonanywhere.com/publicaciones" class="text-reset">Celulares</a>
            </h6>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Links Utiles
            </h6>
            <h6>
              <a href="{% url 'acerca' %}" class="text-reset">Acerca de nosotros</a>
            </h6>
            <h6>
              <a href="{% url 'faq' %}" class="text-reset">Preguntas frecuentes</a>
            </h6>
            <h6>
              <a href="{% url 'terminos' %}" class="text-reset">Términos y condiciones</a>
            </h6>
            <h6>
              <a href="{% url 'privacidad' %}" class="text-reset">Politica de privacidad</a>
            </h6>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contacto</h6>
            <h6><i class="bi bi-house-check"></i> Mitre 4025, Villa Fiorito, Argentina</h6>
            <h6>
              <i class="bi bi-envelope-at"></i>
              info@example.com
            </h6>
            <h6><i class="bi bi-phone-vibrate"></i> + 01 234 567 88</h6>
            <h6><i class="bi bi-telephone-inbound"></i> + 01 234 567 89</h6>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4 texto">
      <h6>Donde cada articulo encuentra su lugar</h6>
      <h6 class="text-reset fw-bold" href="https://circular.pythonanywhere.com/">CirculAR</h6>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

PruebaCirculAR/templates/file_header.html
  {% load static %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'Style.css' %}">
  <div class="class1">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid fw-bold text-decoration-none">
            
          {% if user.is_authenticated %}
          <a class="navbar-brand logo " href="{% url 'home' %}">
            <img src="{% static 'logo4 copia.png' %}" width="90" height="80"><a></a>
            
        </a>  
        <a class="navbar-brand title-text mx-auto" href="{% url 'home' %}">
          <span class="title-highlight">CirculAR</span>
        </a>
		{% if notificacion %}
		<a href="{% url 'inbox:inbox' %}"><img src="{% static 'new-message.gif' %}" alt="Mensaje" width="70" class="me-4"></a>
		{% else %}
		<a href="{% url 'inbox:inbox' %}"><img src="{% static 'sinMensaje.gif' %}" alt="Mensaje" width="70" class="me-4"></a>
		{% endif %}
      <ul class="nav justify-content-end">
            <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                  <img src="{{ request.user.avatar.url }}" alt="usuario" width="80" class="rounded-circle me-2">
                </a>
                <ul class="dropdown-menu text-small dropdown-menu-end" aria-labelledby="dropdownUser1">
                  <li><a class="dropdown-item" href="{% url 'Usuarios:misDatos' %}">Mis Datos</a></li>
                  <li><a class="dropdown-item" href="{% url 'publicacion:lista_publicaciones' %}">Mis Publicaciones</a></li>
                  <li><a class="dropdown-item" href="{% url 'Usuarios:modificar' %}">Modificar datos</a></li>
                  <li><a class="dropdown-item" href="{% url 'Usuarios:eliminar' %}">Eliminar cuenta</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'Usuarios:salir' %}" onclick="return confirm('¿Confirma que desea salir?');">Salir</a></li>
                </ul>
            </div>
            {% else %}
            <a class="navbar-brand logo " href="{% url 'home' %}">
              <img src="{% static 'logo4 copia.png' %}" width="90" height="80"><a></a>
              
          </a>  
          <div class="no-select" style="color:white">CirculAR CirculAR CirculAR</div>
          <a class="navbar-brand title-text mx-auto" href="{% url 'home' %}">
            <span class="title-highlight">CirculAR</span>
          </a>
        <ul class="nav justify-content-end">
            <div class="navbar-nav mx-auto mb-2 mb-lg-0">
              <li>
                  <a class="nav-link1" href="{% url 'Usuarios:ingresar' %}">Ingresar</a>
                  <img src="{% static 'key-person_16104343.gif' %}" alt="Ingresar" width="64">
              </li>
              <li>
                  <div class="d-none d-lg-flex mx-lg-2 text-black"></div>
                <hr class="d-lg-none my-2 text-black-50">
              </li>
              <li>
                <a class="nav-link1" href="{% url 'Usuarios:registrar' %}">Registrarse</a>
                <img src="{% static 'registered_17626906.gif' %}" alt="Registrarse" width="64">
                  
              </li>
            </div>
            {% endif %}
          </ul>
        <!-- Botón del toggle para móviles -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>

    <!-- Barra de navegación con las opciones centradas debajo del título -->
    
    <nav class="navbar navbar-expand-lg bg-body-tertiary texto">  
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Sección izquierda (vacía para balance) -->
          <div class="no-select navbar-nav flex-grow-1"style="color:#2a3c57";>CirculAR CirculAR CirculAR CirculAR</div>
          
          <!-- Sección central (navegación) -->
          <ul class="navbar-nav mb-2 mb-lg-0 me-5">
            <li class="nav-item mx-2 me-5">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item mx-2 me-5">
              <a class="nav-link" href="{% url 'publicacion:publicaciones' %}">Productos</a>
            </li> 
            <li class="nav-item mx-2 me-5">
              <a class="nav-link" href="{% url 'compra:trueque_realizado' %}">Trocar</a>
            </li> 
            <li class="nav-item mx-2 me-5">
              <a class="nav-link" href="{% url 'publicacion:nuevaPublicacion' %}">Vender</a>
            </li>
            <li class="nav-item dropdown mx-2 me-5">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Shop
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#novedades">Novedades</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#ofertas">Ofertas de la Semana</a></li>
              </ul>
            </li>
          </ul> 
          
          <!-- Sección derecha (búsqueda) -->
          <div class="navbar-nav flex-grow-1 justify-content-end">
            <form class="d-flex" action="{% url 'publicacion:buscar_publicacion' %}" method="GET" role="search">
              <button class="btn btn-info btn-lg" type="submit">
                <i class="bi bi-search"></i>
              </button>
            </form>
          </div>
        </div>
      </div>
    </nav>
    
    <div class='texto1 mt-1'>
      <p>¡Esperamos que disfrutes de una experiencia de compra-venta inigualable y encuentres exactamente lo que buscas!</p>
    </div>
          

PruebaCirculAR/templates/help.html
{% extends "tasks/base.html" %}
{% block content %}
<div class="container mt-4">
<div class="card">
<div class="card-header">
Help Page
</div>
<div class="card-body">
<h5 class="card-title">What is a task manager?</h5>
<p class="card-text">A task management system is software
that helps users organize and track the progress of tasks.
</p>
<a href="/" class="btn btn-primary">Go Home</a>
</div>
</div>
</div>
{% endblock %}

PruebaCirculAR/templates/home.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'static/Style.css' %}">
<div class="container">
    <div class="row">
        <div class="col-lg-3"> 
        </div>
        <div class="col-lg-20 mt-4">
            {% if user.is_authenticated %}
                <img src="{% static 'ok2.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Imagen Usuario Logueado">
            {% else %}
                <img src="{% static 'ok1.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Imagen Usuario No Logueado">
            {% endif %}
        </div>
    </div>
</div>
    <div class="container">
        {% if user.is_authenticated %}
        <div class="row align-items-center">
            <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-5">
                <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Bienvenidos</h1>
            </div>
        </div>            
        
        {% else %}
        <div class="row align-items-center">  
            <div class="d-grid gap-2 d-md-flex justify-content-md-center mt-5">
                <a href="{% url 'Usuarios:registrar' %}"><span class="btn btn-info" >Registrarse</span></a>
            </div>            
        </div>
        {% endif %}
    </div>
       
    </div> 
    <br>
    <div class="container">

    <h3>Rubros</h3>
    <hr class="my-4">
   
   
        <div class="card border-light">
            <div class="card-body">
                <div class="row row-cols-1 row-cols-md-4 g-4">
        
        
                    {% for rubro in rubro %}
                    <div class="col">
                        <div class="card h-100">
         
                            
                            <div class="d-flex justify-content-center mb-3 mt-3">
                            <a href="{% url 'publicacion:publicaciones_filtradas' rubro.id %}"><span class="btn btn-success"  >{{ rubro.nombre }}</span></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}   
    </div>
    </div>
    </div>
    </div>
    <br>
    <br>
    <div class="container" id="novedades">
    <h3 >Novedades</h3>

    <hr class="my-4">
    
    <div class="card border-light">
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for publicacion in lista_prod_last %}
    
    <div class="col">
        <a href="{% url 'publicacion:mostrar_publicacion' id=publicacion.id %}" class="text-decoration-none text-dark card-link">
            <div class="card h-100 card-hover">
                <div class="image-container">
                    <img src="{{ publicacion.producto.imagen_1.url }}" class="card-img-top card-img-hover" alt="Imagen del producto">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ publicacion.nombre }}</h5>
                    <p class="card-text">{{ publicacion.descripcion }}</p>
                    <p class="card-text"><small class="text-body-secondary">${{ publicacion.valor }}</small></p>
                </div>
            </div>
        </a>
    </div>


    {% endfor %}
</div>
</div>
</div>
</div>

    <br>
    <div class="container">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
                aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"
                aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2"
                aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'mujer.jpg' %}" class="d-block w-100" alt="...">
                
            </div>
            <div class="carousel-item">
                <img src="{% static 'hotdsale.jpg' %}" class="d-block w-100" alt="...">
                
            </div>
            <div class="carousel-item">
                <img src="{% static 'coca_cola1.jpg' %}" class="d-block w-100" alt="...">
                
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    </div>

<br>

<div class="container" id="ofertas">
<h3>Ofertas de la Semana</h3>
<hr class="my-4">

    <div class="card border-light">
        <div class="card-body">
            <div class="row row-cols-1 row-cols-md-4 g-4">
    {% for publicacion in lista_prod_rand %}
    
    <div class="col">
        <a href="{% url 'publicacion:mostrar_publicacion' id=publicacion.id %}" class="text-decoration-none text-dark card-link">
            <div class="card h-100">
                <div class="image-container">
                    <img src="{{ publicacion.producto.imagen_1.url }}" class="card-img-top card-img-hover" alt="Imagen del producto">
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ publicacion.nombre }}</h5>
                    <p class="card-text">{{ publicacion.descripcion }}</p>
                    <p class="card-text"><small class="text-body-secondary">${{ publicacion.valor }}</small></p>
                </div>
            </div>
        </a>
    </div>
    


    {% endfor %}
</div>
</div>
</div>
</div>

<br>
<br>

{% endblock %}

PruebaCirculAR/templates/search.html
{% extends "tasks/base.html" %}
{% block content %}
<div class="container">

    <div class="card text-center">
        <div class="card-header">
          Busquedas
        </div>
        <div class="card-body">
          <p class="card-text">Ingrese el nombre o algo de la descripción de lo que desea buscar.</p>
    
          <form method="POST" actions="{% url 'search' %}">
            {% csrf_token %}
            <div class="mb-3">
                <input type="text" class="form-control" placeholder="Buscar Productos" name="searched">
            </div>
            <button type="submit" class="btn btn-success">
                Buscar Productos
            </button>                 

          </form>
        </div>
        
    </div>
    <br/>
    <br/>
    {% if searched %}

    <div class="row row-cols-1 row-cols-md-3 g-4">
      
      {% for Product in searched %}
      
      <div class="col">
        <div class="card border-success mb-3">
          
          <div class="card-body">
            
            <img src="/{{ Product.imagen_1 }}" class="bd-placeholder-img card-img-top" width="100" height="300">
                    
          </div>
          <div class="card-footer bg-transparent">
            <ul class="list-unstyled mt-3 mb-4">
              <li>{{ Product.name }}</li>
              <li>{{ Product.precio }}</li>                    
            </ul>
    
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-danger">Comprar</button>
                
              </div>
              <small class="text-body-secondary">9 mins</small>
            </div>
          </div>
        </div>
      </div>

      {% endfor %}
     
    </div>  

    {% endif %}

    <div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div class="col-10 col-sm-8 col-lg-6"> 
        
        {% load static %}
        <img src="{% static 'tasks/electros.png' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
        </div>
        <div class="col-lg-6">
        <h1 class="display-5 fw-bold text-body-emphasis lh-1 mb-3">Solo requiere Registrarse</h1>
        <p class="lead">Ingresa a una de las mejores y mas difundidas paginas dedicadas a la venta de usados. Cientos de usuarios avalan nuestra experiencia. Sin tasas ocultas, sin gastos, solo el deseo de que puedas vender/comprar un usado</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
            <a href="{% url 'register_user' %}"><span class="btn btn-success">Registrarse</span></a>  
            
        </div>
        </div>
    </div>
    </div>


  

</div>
 

{% endblock %}