PruebaCirculAR/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('', include('Usuarios.urls',namespace='Usuarios')),
    path('', include('publicacion.urls',namespace='publicacion')),
    path('', include('compra.urls', namespace='compra')),
    path('',include('api.urls', namespace='api')),
    path('', include('inbox.urls',namespace='inbox')),
    path('', include('venta.urls',namespace='venta')),
    path('acerca/', views.acerca, name='acerca'),
    path('faq/', views.faq, name='faq'),
    path('terminos/', views.terminos, name='terminos'),
    path('privacidad/', views.privacidad, name='privacidad'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('procesar_pago/<int:publicacion_id>/', views.procesar_pago, name='procesar_pago'),
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('pago_fallido/', views.pago_fallido, name='pago_fallido'),
    path('pago_pendiente/', views.pago_pendiente, name='pago_pendiente'),
]

compra/urls.py
from django.urls import path
from . import views
from .views import trueque_realizado

app_name = 'compra'
urlpatterns = [
path('realizar_compra/<int:id>/', views.realizar_compra, name='realizar_compra'),
path('compra/compras_realizadas/', views.compras_realizadas, name='compras_realizadas'),
path('pago_efectivo/<int:publicacion_id>/', views.pago_efectivo, name='pago_efectivo'),
path('pago_transferencia/<int:publicacion_id>/', views.pago_transferencia, name='pago_transferencia'),
path('trueque/<int:publicacion_id>/', views.trueque_view, name='trueque'),
path('compra/trueque_realizado/', trueque_realizado, name='trueque_realizado'),
path('compra/publicado/<int:publicacion_id>/', views.publicado, name='publicado'),
path('compra/nuevoproducto/<int:publicacion_id>/', views.nuevo_producto, name='nuevo_producto'),
]

publicacion/urls.py
from django.urls import path
from . import views

app_name = 'publicacion'
urlpatterns = [
    path('publicaciones',views.publicaciones,name='publicaciones'),
    path('publicaciones_filtradas/<int:id>',views.publicaciones_filtradas,name='publicaciones_filtradas'),
    path('nueva_publicacion',views.nuevaPublicacion,name='nuevaPublicacion'),
    path('lista_publicaciones',views.lista_publicaciones,name='lista_publicaciones'),
    path('mostrar_publicacion/<int:id>',views.mostrar_publicacion,name='mostrar_publicacion'),
    path('modificar_publicacion/<int:id>',views.modificar_publicacion,name='modificar_publicacion'),
    path('eliminar_publicacion/<int:id>',views.eliminar_publicacion,name='eliminar_publicacion'),
    path ('buscar_publicacion', views.search, name='buscar_publicacion'),
]

venta/urls.py
from django.urls import path
from . import views

app_name = 'venta'
urlpatterns = [
    #path('venta/ventas_realizadas/', views.ventas_realizadas, name='ventas_realizadas'),
    path('ventas_realizadas/', views.ventas_realizadas, name='ventas_realizadas'),
    path('trueque/<int:trueque_id>/responder/<str:accion>/', views.responder_trueque, name='responder_trueque'),
    ]

compra/models.py
from django.db import models
from Usuarios.models import CustomUser
from publicacion.models import Publicacion, Producto
from django.conf import settings


MEDIO_PAGO_CHOICES = [
    ('EFECTIVO', 'pago_efectivo'),
    ('TRANSFERENCIA', 'pago_transferencia'),
    ('MERCADOPAGO', 'api:procesar_pago'),
    ('TRUEQUE', 'trueque'),
]

class Compra(models.Model):
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE,null=True)
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True)
    numeroComprobante = models.CharField(max_length=255, blank=True, null=True)
    imagen = models.ImageField(upload_to='comprobantes/', blank=True, null=True)
    fechaDeTransferencia = models.DateField(blank=True, null=True)
    fecha_compra = models.DateTimeField(auto_now_add=True, null=True)
    medio_pago = models.CharField(max_length=20, choices=MEDIO_PAGO_CHOICES)

    def __str__(self):
        return f"Compra {self.id} realizada el {self.fecha_compra}"

    
class Trueque(models.Model):
    usuario = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    publicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE,null=True)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, null=True)
    producto_ofrecido = models.TextField()
    imagen1 = models.ImageField(upload_to='trueque_images/', null=True, blank=True)
    imagen2 = models.ImageField(upload_to='trueque_images/', null=True, blank=True)

    vendedor_respondio = models.BooleanField(default=False)

    respuesta_vendedor = models.TextField(blank=True, null=True)  # Campo para contraoferta o mensaje de respuesta
    estado_trueque = models.CharField(max_length=10,choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')],default='pendiente')

    def __str__(self):
        return self.producto_ofrecido

compra/forms.py
from django import forms
from .models import Compra, Trueque

 

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['numeroComprobante', 'imagen', 'fechaDeTransferencia']

        labels = {
            'numeroComprobante':'comprobante',
            'imagen':'adjuntar archivo',
            'fechaDeTransferencia':'fecha Transferencia ',
            
            
                 }
        
        widgets = {
            'numeroComprobante':forms.TextInput(attrs={'class':'form-control ms-4', 'style':'width: 103%'}),
            'fechaDeTransferencia':forms.DateInput(attrs={'type':'date','class':'form-control ms-4', 'style':'width: 103%'}),
            'imagen':forms.FileInput(attrs={'class':'form-control ms-4', 'style':'width: 103%'}),
            
        }
       
            
class TruequeForm(forms.ModelForm):
    class Meta:
        model = Trueque
        fields = ['producto_ofrecido', 'imagen1', 'imagen2']
        labels = {
            'producto_ofrecido':'',
            'imagen1':'',
            'imagen2':'',
             }
        widgets = {
            'producto_ofrecido': forms.Textarea(attrs={'placeholder': 'Describe el producto que ofreces para el trueque','class':'form-control mt-2', 'style':'width: 108%;'}),
            'imagen1':forms.FileInput(attrs={'class':'form-control', 'style':'width: 108%;'}),
            'imagen2':forms.FileInput(attrs={'class':'form-control', 'style':'width: 108%;'}),
        }

compra/views.py
from django.shortcuts import get_object_or_404,render, redirect
from django.template import TemplateDoesNotExist
from .models import Publicacion, Compra, Trueque
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect
from django.conf import settings
from django.urls import reverse
from .forms import CompraForm, TruequeForm
from inbox.views import notificacion




@login_required
def realizar_compra(request, id):
    # Obtén la publicación con el id dado

    publicacion = Publicacion.objects.get (id=id)
    if publicacion.usuario == request.user:
       
        messages.error(request, 'No puedes comprar tu propia publicación.')
        return redirect('publicacion:lista_publicaciones')  
    if request.method == 'POST':
        medio_pago = request.POST.get('medio_pago')
        
        # Redirigir según el medio de pago seleccionado
        if medio_pago == 'EFECTIVO':
           return redirect('compra:pago_efectivo', publicacion_id=publicacion.id)
        elif medio_pago == 'TRANSFERENCIA':
            return redirect('compra:pago_transferencia', publicacion_id=publicacion.id)
        elif medio_pago == 'MERCADOPAGO':
            #return redirect('crear_preferencia', publicacion_id=publicacion.id)
            return redirect('api:procesar_pago', publicacion_id=publicacion.id)
        elif medio_pago == 'TRUEQUE':
            return redirect('compra:trueque', publicacion_id=publicacion.id)
        
        publicacion.vigencia=3  # Establecer a 'SUSPENDIDO'
        publicacion.save()
        return redirect('compra:compras_realizadas')  
    
    return render(request, 'realizar_compra.html', {'publicacion': publicacion})

@login_required
def pago_efectivo(request, publicacion_id):
    publicacion = get_object_or_404(Publicacion, id=publicacion_id)

    if request.method == 'POST':
        # Crear y guardar la compra en la base de datos
        compra = Compra(
            publicacion=publicacion,
            usuario=request.user,
            medio_pago='efectivo'
        )
        compra.save()
        pago_confirmado = True  # Cambia esta condición según tu lógica de pago

        if pago_confirmado:
            publicacion.vigencia = 3  # Establecer a 'SUSPENDIDO'
            publicacion.save()
            messages.success(request, 'Compra realizada con éxito.')
            return redirect('compra:compras_realizadas')
        else:
            messages.error(request, 'El pago no pudo ser procesado.')
            return redirect('publicacion:lista_publicaciones')

    return render(request, 'pago_efectivo.html', {'publicacion': publicacion})


def compras_realizadas(request):
    #lista_compra = Compra.objects.filter(usuario=request.user,).order_by('-id')
    #lista_compra = Compra.objects.all().order_by('-id').filter(usuario=request.user.id)
    #lista_compra = Compra.objects.filter(usuario=request.user).order_by('-id')
    lista_compra = Compra.objects.filter(usuario=request.user).order_by('-id')
    print(lista_compra)

    context = {
        'compras_realizadas': lista_compra
    }
    #return redirect(reverse('compras_realizadas', args=[publicacion_id]))
    return render(request, 'compras_realizadas.html', context)

@login_required
def pago_transferencia(request, publicacion_id): 
    publicacion = get_object_or_404(Publicacion, id=publicacion_id)
    
    if request.method == 'POST':
        form = CompraForm(request.POST, request.FILES)
        if form.is_valid():
            # Guarda el formulario y la información del comprobante
            compra = form.save(commit=False)
            compra.publicacion = publicacion
            compra.usuario = request.user
            compra.metodo_pago = 'transferencia'
            compra.save()
            pago_confirmado = True  # Cambia esta condición según tu lógica

        if pago_confirmado:
            publicacion.vigencia = 3  # Establecer a 'SUSPENDIDO'
            publicacion.save()
            messages.success(request, 'Compra realizada con éxito.')
        return redirect('compra:compras_realizadas')
    else:
        form = CompraForm()  # Esta línea asegura que 'form' se defina siempre, incluso si no es POST.
    
    return render(request, 'pago_transferencia.html', {
        'publicacion': publicacion,
        'form': form
    })


def trueque_view(request, publicacion_id):
    publicacion = get_object_or_404(Publicacion, id=publicacion_id)
    
    if request.method == 'POST':
        trueque = request.POST.get('producto')
        
        # Redirigir según el medio de pago seleccionado
        if trueque == 'publicado':
           return redirect('compra:publicado', publicacion_id=publicacion.id)
        elif trueque == 'nuevoproducto':
            return redirect('compra:nuevo_producto', publicacion_id=publicacion.id)
       
      
        publicacion.vigencia=3  # Establecer a 'SUSPENDIDO'
        publicacion.save()
        return redirect('compra:trueque_realizado')  
    
    return render(request, 'trueque.html', {'publicacion': publicacion})

def publicado(request, publicacion_id):
    publicacion = get_object_or_404(Publicacion, id=publicacion_id)
    
    # Obtener las publicaciones disponibles para trueque que no están vendidas (estado != 'vendida')
    lista_publicaciones = Publicacion.objects.filter(usuario=request.user, vigencia=1)
    #lista_publicaciones = Publicacion.objects.filter(usuario=request.user).exclude(estado=3)  # estado '1' es el estado disponible
   
    
    if request.method == 'POST':
        # Verificar si el usuario ha seleccionado una publicación
        publicacion_seleccionada_id = request.POST.get('publicacion_seleccionada_id')

        if publicacion_seleccionada_id:
            # Verificar que la publicación seleccionada esté en estado '1' (disponible para trueque)
            publicacion_seleccionada = get_object_or_404(Publicacion, id=publicacion_seleccionada_id)

            # Crear el trueque
            trueque = Trueque(usuario=request.user, publicacion=publicacion)
            trueque.producto_ofrecido = publicacion_seleccionada.nombre  # Asocia el nombre de la publicación
            trueque.producto = publicacion_seleccionada.producto
            trueque.save()

            trueque_confirmado = True

            if trueque_confirmado:
                publicacion.vigencia = 3  # Establecer a 'SUSPENDIDO'
                publicacion.save()


            # Notificación y mensaje de éxito
            notificacion(request, publicacion, 3)
            messages.success(request, 'Has ofrecido tu producto para el trueque exitosamente.')
            return redirect('compra:trueque_realizado')

        else:
            messages.error(request, "Debe seleccionar una publicación válida para el trueque.")
    
    return render(request, 'publicado.html', {
        'publicacion_id': publicacion_id,
        'lista_publicaciones': lista_publicaciones
    })
@login_required
def ofrecer_trueque(request, publicacion_id,):
    publicacion = get_object_or_404(Publicacion, id=publicacion_id)
    # Lógica para crear el trueque
    trueque = Trueque.objects.create(
        publicacion=publicacion,
        usuario=request.user,
        estado_trueque='pendiente'
    )
    messages.success(request, '¡Has ofrecido el trueque con éxito!')

    # Redirigir a la vista de trueque_realizado
    return redirect('compra:trueque_realizado')

def nuevo_producto(request, publicacion_id):
    publicacion = get_object_or_404(Publicacion, id=publicacion_id)

    if request.method == 'POST':
        form = TruequeForm(request.POST, request.FILES)
        if form.is_valid():
            
            trueque = form.save(commit=False)
            trueque.usuario = request.user  # Asocia el usuario actual
            
            trueque.publicacion = publicacion  # Asocia la publicación correspondiente
            trueque.save()

            trueque_aprobado = True

            if trueque_aprobado:
                publicacion.vigencia = 3  # Establecer a 'SUSPENDIDO'
            trueque_rechazado = False
            if trueque_rechazado:
                publicacion.vigencia = 1
                publicacion.save()
                
            notificacion(request,publicacion,3)
            messages.success(request, 'Has ofrecido tu producto para el trueque exitosamente. El vendedor responderá a la brevedad.')
            return redirect('compra:trueque_realizado')

    else:
        form = TruequeForm()

    return render(request, 'nuevo_producto.html', {'form': form, 'publicacion_id': publicacion_id})
   
@login_required
def trueque_realizado(request):
    # Trueques donde el usuario es quien hizo la oferta (ofrecidos)
    trueques_ofrecidos = Trueque.objects.filter(usuario=request.user).order_by('-id')
 
    # Trueques donde el usuario es el dueño de la publicación (recibidos)
    trueques_recibidos = Trueque.objects.filter(publicacion__usuario=request.user).order_by('-id')
   
    context = {
        'trueques_ofrecidos': trueques_ofrecidos,
        'trueques_recibidos': trueques_recibidos,
    }
    
    return render(request, 'trueque_realizado.html', context)

compra/templates/compra_confirmacion.html
{% extends "base.html" %}
{% block content %}
    <title>Confirmación de Compra</title>
    
    <h1>¡Gracias por tu compra!</h1>
    
    <p>Tu compra ha sido realizada con éxito.</p>
    <p>Nos pondremos en contacto contigo para coordinar la entrega y el pago, si corresponde.</p>
    
    <h2>Detalles de la compra:</h2>
    <p><strong>Producto:</strong> {{ publicacion.nombre }}</p>
    <p><strong>Precio:</strong> ${{ publicacion.valor }}</p>
    
    <h3>¿Qué hacer a continuación?</h3>
    <p>Por favor, verifica tu correo electrónico para obtener más información.</p>

    <a href="{% url 'compra:compras_realizadas' publicacion.id %}">Volver al inicio</a>
{% endblock %}

compra/templates/compras_realizadas.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <br>
    <br>
    <ul class="nav nav-tabs">
       
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'publicacion:lista_publicaciones' %}">Mis Publicaciones</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark active" aria-current="page" href="{% url 'compra:compras_realizadas' %}">Mis Compras</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'compra:trueque_realizado' %}">Mis Trueques</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'venta:ventas_realizadas' %}">Mis Ventas</a>
        </li>
    </ul>
    <br>
    <h1>Lista de compras:</h1>
    <br>
    <br>
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 22%;">NOMBRE DE LA PUBLICACIÓN</th>
                    <th style="width: 22%;">PRECIO</th>
                    <th style="width: 22%;">IMAGEN</th>
                </tr>
            </thead>
            <tbody>
                {% for compra in compras_realizadas %}
                <tr>   
                    <td>{{ compra.publicacion.nombre }}</td>
                    <td>{{ compra.publicacion.valor }}</td>
                    <td><svg class="bi" width="24" height="24"></svg>
                        <img src="{{ compra.publicacion.producto.imagen_1.url }}" class="img-fluid" width="100" height="100" />
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">No tienes compras realizadas.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

compra/templates/nuevo_producto.html
{% extends "base.html" %}
{% block content %}
<h2 class="mx-auto">Ofrecer Producto para Trueque</h2>
<div>
    <div class="card w-75 mt-3 mb-3">
        <div class="card-body texto">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success btn-lg m-1">Enviar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

compra/templates/pago_efectivo.html
{% extends "base.html" %}
{% block content %}
{% load static %}
    <title>Pago en Efectivo</title>
    
    <h1 class="m-3">Pago en Efectivo</h1>
    <p class="m-3">Estás comprando: {{ publicacion.nombre }}</p>
    <p class="m-3">Precio: {{ publicacion.valor }}</p>
    <form method="post">
        {% csrf_token %}

        <button type="submit" class="btn btn-success m-3">Confirmar Pago</button>
        <a href="{% url 'compra:realizar_compra' publicacion.id %}"><span class="btn btn-danger m-3">Cancelar</span></a>
    </form>
    <img src="{% static 'efectivo1.gif' %}" alt="Descripción de la imagen" class="img-fluid" style="max-width: 15%; height: auto;">
{% endblock %}

compra/templates/pago_transferencia.html
{% extends "base.html" %}
{% block content %}
<title>Pago por Transferencia Bancaria/Depósito</title>

    <div class="card mt-4 mb-2 w-75 box">
        <div class="card-body">
            <h1>Pago por Transferencia Bancaria/Depósito</h1>
            <p>Estás comprando: {{ publicacion.nombre }}</p>
            <p>Por favor, realiza la transferencia bancaria o depósito usando los siguientes datos:</p>

            <h2>Datos de la Cuenta:</h2>
            <p><strong>Banco:</strong> [Nombre del Banco]</p>
            <p><strong>Nombre del Titular:</strong> [Nombre del Titular]</p>
            <p><strong>Cuenta:</strong> [Número de Cuenta]</p>
            <p><strong>CBU:</strong> [CBU]</p>
            <p><strong>Alias:</strong> [Alias]</p>
            <p><strong>Importe:</strong> [Monto a Transferir]</p>

            <p>Una vez realizada la transferencia o depósito, por favor confirma el pago completando el siguiente formulario:</p>
        </div>
    </div>
    
    <form class="texto w-75 mb-3 mt-3 pt-3"method="post">
        
        {% csrf_token %}
        {{ CompraFormSet.as_p }}
        {{ form.as_p }}
    
        
        <button type="submit" class="btn btn-success m-3">Confirmar Pago</button>
        <a href="{% url 'compra:realizar_compra' publicacion.id %}"><span class="btn btn-danger m-3">Cancelar</span></a>
    </form>
    {% endblock %}

compra/templates/publicado.html
{% extends "base.html" %}

{% block content %}
{% load static %}
<h1 class="m-5">Selecciona una publicación para ofrecer en el trueque</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- Mostrar las publicaciones disponibles para el trueque -->
    <div class="row">
        {% if lista_publicaciones %}
            {% for publicacion in lista_publicaciones %}
                <div class="col-md-3 mb-5">
                    <div class="card card-link">
                        <div class="image-container">
                            <img src="{{ publicacion.producto.imagen_1.url }}" alt="{{ publicacion.nombre }}" class="card-img-top">
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{ publicacion.nombre }}</h5>
                            <p class="card-text">{{ publicacion.descripcion }}</p>
                            <div class="d-flex justify-content-center">
                                <button type="submit" name="publicacion_seleccionada_id" value="{{ publicacion.id }}" class="btn btn-primary">Seleccionar esta publicación</button>
                            </div>
                            <div class="d-flex justify-content-center">
                                <a href="{% url 'compra:realizar_compra' publicacion.id %}" class="btn btn-danger mt-2">Cancelar</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-12 text-center">
                <p>No tienes publicaciones disponibles para ofrecer en trueque.</p>
            </div>
        {% endif %}
    </div>

</form>

<!-- Mostrar mensajes -->
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li>{{ message }}</li>
        {% endfor %} 
    </ul>
{% endif %}
{% endblock %}

compra/templates/trueque_realizado.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <br><br>
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'publicacion:lista_publicaciones' %}">Mis Publicaciones</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'compra:compras_realizadas' %}">Mis Compras</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark active" aria-current="page" href="{% url 'compra:trueque_realizado' %}">Mis Trueques</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" href="{% url 'venta:ventas_realizadas' %}">Mis Ventas</a>
        </li>
    </ul>
    <br>

    <!-- Tabla de Trueques Realizados -->
    <h1>Trueques Realizados</h1>
    <br>
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 18%;">NOMBRE DE LA PUBLICACIÓN</th>
                    <th style="width: 18%;">PRODUCTO OFRECIDO</th>
                    <th style="width: 18%;">PRECIO</th>
                    <th style="width: 18%;">IMÁGENES</th>
                    <th style="width: 10%;">ESTADO</th>
                </tr>
            </thead>
            <tbody>
                {% if trueques_ofrecidos %}
                    {% for trueque in trueques_ofrecidos %}
                        <tr>
                            <td>{{ trueque.publicacion.nombre }}</td>
                            <td>{{ trueque.producto_ofrecido }}</td>
                            <td>{{ trueque.publicacion.valor }}</td>
                            <td>
                                {% if trueque.imagen1 %}
                                    <img src="{{ trueque.imagen1.url }}"  class="card-img-top">
                                {% elif trueque.producto.imagen_1 %}
                                    <img src="{{ trueque.producto.imagen_1.url }}" alt="Imagen de la publicación" class="card-img-top">
                                {% else %}
                                    <img src="{% static 'images/sin_avatar.png' %}" alt="Imagen predeterminada" class="card-img-top">
                                {% endif %}
                            </td>
                                <strong>Estado del trueque:</strong> 
                                {% if trueque.respuesta_vendedor %}
                                    {% if trueque.estado_trueque == 'aceptado' %}
                                        Aceptó el trueque.
                                    {% elif trueque.estado_trueque == 'rechazado' %}
                                        Rechazó el trueque.
                                    {% else %}
                                        Estado desconocido.
                                    {% endif %}
                                {% else %}
                                    El vendedor no ha respondido aún.
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="6">No has realizado ningún trueque.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>

    <!-- Tabla de Trueques Recibidos -->
    <h1>Trueques Recibidos</h1>
    <br>
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th style="width: 18%;">NOMBRE DE LA PUBLICACIÓN</th>
                    <th style="width: 18%;">PRODUCTO OFRECIDO</th>
                    <th style="width: 18%;">USUARIO OFERENTE</th>
                    <th style="width: 18%;">IMAGEN</th>
                    <th style="width: 10%;">ACCIONES</th>
                </tr>
            </thead>
            <tbody>
                {% if trueques_recibidos %}
                    {% for trueque in trueques_recibidos %}
                        <tr>
                            <td>{{ trueque.publicacion.nombre }}</td>
                            <td>{{ trueque.producto_ofrecido }}</td>
                            <td>{{ trueque.usuario.username }}</td>
                            <td>
                                {% if trueque.imagen1 %}
                                    <img src="{{ trueque.imagen1.url }}" alt="Imagen del producto ofrecido" class="card-img-top">
                                {% elif trueque.producto.imagen_1 %}
                                    <img src="{{ trueque.producto.imagen_1.url }}" alt="Imagen de la publicación" class="card-img-top">
                                {% else %}
                                    <img src="{% static 'images/sin_avatar.png' %}" alt="Imagen predeterminada" class="card-img-top">
                                {% endif %}
                            </td>
                            <td>
                                {% if trueque.estado_trueque == 'pendiente' %}
                                    <a href="{% url 'venta:responder_trueque' trueque.id 'aceptado' %}" class="btn btn-success btn-sm mb-4">Aceptar</a>
                                    <a href="{% url 'venta:responder_trueque' trueque.id 'rechazado' %}" class="btn btn-danger btn-sm mb-4">Rechazar</a>
                                {% else %}
                                    <span>Trueque {{ trueque.estado_trueque }}</span>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="6">No tienes ninguna publicacion para ofrecer trueque.</td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}